=== LosoncziDominik/HZ60V1WebXML/HZ60V1_XMLTask/HZ60V1DOMParse/HZ60V1_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="HZ60V1_mozi">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mozi" type="moziTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="dolgozó" type="dolgozóTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="terem" type="teremTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="film" type="filmTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="vásárló" type="vásárlóTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="jegy" type="jegyTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="büfé" type="büféTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="Mkod" type="xs:ID"></xs:attribute>
        </xs:complexType>

        <!-- Kulcsok-->

        <xs:key name="Mozi_kulcs">
            <xs:selector xpath="mozi"/>
            <xs:field xpath="@Mkod"/>
        </xs:key>

        <xs:key name="Dolgozó_kulcs">
            <xs:selector xpath="dolgozó"/>
            <xs:field xpath="@Dkod"/>
        </xs:key>

        <xs:key name="Terem_kulcs">
            <xs:selector xpath="terem"/>
            <xs:field xpath="@Tkod"/>
        </xs:key>

        <xs:key name="Film_kulcs">
            <xs:selector xpath="film"/>
            <xs:field xpath="@Fkod"/>
        </xs:key>

        <xs:key name="Vásárló_kulcs">
            <xs:selector xpath="vásárló"/>
            <xs:field xpath="@Vkod"/>
        </xs:key>

        <xs:key name="Jegy_kulcs">
            <xs:selector xpath="jegy"/>
            <xs:field xpath="@Jkod"/>
        </xs:key>

        <xs:key name="Büfé_kulcs">
            <xs:selector xpath="büfé"/>
            <xs:field xpath="@Bkod"/>
        </xs:key>

        <!-- Idegen kulcsok-->

        <xs:keyref name="Dolgozó_Mozi_FK" refer="Mozi_kulcs">
            <xs:selector xpath="dolgozó"/>
            <xs:field xpath="@M_D"/>
        </xs:keyref>

        <xs:keyref name="Terem_Mozi_FK" refer="Mozi_kulcs">
            <xs:selector xpath="terem"/>
            <xs:field xpath="@M_T"/>
        </xs:keyref>

        <xs:keyref name="Film_Mozi_FK" refer="Mozi_kulcs">
            <xs:selector xpath="film"/>
            <xs:field xpath="@M_F"/>
        </xs:keyref>

        <xs:keyref name="Vásárló_Jegy_FK" refer="Jegy_kulcs">
            <xs:selector xpath="vásárló"/>
            <xs:field xpath="@J_V"/>
        </xs:keyref>

        <xs:keyref name="Jegy_Mozi_FK" refer="Mozi_kulcs">
            <xs:selector xpath="jegy"/>
            <xs:field xpath="@M_J"/>
        </xs:keyref>

        <xs:keyref name="Büfé_Mozi_FK" refer="Mozi_kulcs">
            <xs:selector xpath="büfé"/>
            <xs:field xpath="@M_B"/>
        </xs:keyref>

        <xs:unique name="UniqueBufePerMozi">
            <xs:selector xpath="büfé"/>
            <xs:field xpath="@M_B"/>
        </xs:unique>
    </xs:element>

        <!-- Komplex típusok-->

        <xs:complexType name="moziTipus">
            <xs:sequence>
                <xs:element name="név" type="xs:string"></xs:element>
                <xs:element name="cím" type="címTipus"></xs:element>
            </xs:sequence>
            <xs:attribute name="Mkod" type="xs:ID" use="required"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="dolgozóTipus">
            <xs:sequence>
                <xs:element name="név" type="xs:string"></xs:element>
                <xs:element name="műszak" type="xs:string"></xs:element>
                <xs:element name="beosztás" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="Dkod" type="xs:ID" use="required"></xs:attribute>
            <xs:attribute name="M_D" type="xs:IDREF" use="required"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="teremTipus">
            <xs:sequence>
                <xs:element name="férőhely" type="xs:int"></xs:element>
                <xs:element name="típus" type="xs:string"></xs:element>
                <xs:element name="hangrendszer" type="xs:string"></xs:element>
                <xs:element name="extrák" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="Tkod" type="xs:ID" use="required"></xs:attribute>
            <xs:attribute name="M_T" type="xs:IDREF" use="required"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="filmTipus">
            <xs:sequence>
                <xs:element name="cím" type="xs:string"></xs:element>
                <xs:element name="szereplő" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="hossz" type="xs:int"></xs:element>
                <xs:element name="rendező" type="xs:string"></xs:element>
                <xs:element name="értékelés" type="xs:float"></xs:element>
                <xs:element name="év" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="Fkod" type="xs:ID" use="required"></xs:attribute>
            <xs:attribute name="M_F" type="xs:IDREF" use="required"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="vásárlóTipus">
            <xs:sequence>
                <xs:element name="cím" type="címTipus"></xs:element>
                <xs:element name="név" type="xs:string"></xs:element>
                <xs:element name="életkor" type="xs:int"></xs:element>
                <xs:element name="foglalás" type="foglalásTipus"></xs:element>
            </xs:sequence>
            <xs:attribute name="Vkod" type="xs:ID" use="required"></xs:attribute>
            <xs:attribute name="J_V" type="xs:IDREF" use="required"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="jegyTipus">
            <xs:sequence>
                <xs:element name="ár" type="xs:int"></xs:element>
                <xs:element name="kedvezmény" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="Jkod" type="xs:ID" use="required"></xs:attribute>
            <xs:attribute name="M_J" type="xs:IDREF" use="required"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="büféTipus">
            <xs:sequence>
                <xs:element name="étel" type="ételTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="egyéb" type="egyébTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="ital" type="italTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="Bkod" type="xs:ID" use="required"></xs:attribute>
            <xs:attribute name="M_B" type="xs:IDREF" use="required"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="címTipus">
            <xs:sequence>
                <xs:element name="város" type="xs:string"></xs:element>
                <xs:element name="utca" type="xs:string"></xs:element>
                <xs:element name="házszám" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="foglalásTipus">
            <xs:sequence>
                <xs:element name="film_cím" type="xs:string"></xs:element>
                <xs:element name="időpont" type="xs:string"></xs:element>
                <xs:element name="nyelv" type="xs:string"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="ételTipus">
            <xs:sequence>
                <xs:element name="termék" type="xs:string"></xs:element>
                <xs:element name="típus" type="xs:string"></xs:element>
                <xs:element name="ár" type="xs:int"></xs:element>
                <xs:element name="méret" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="egyébTipus">
            <xs:sequence>
                <xs:element name="termék" type="xs:string"></xs:element>
                <xs:element name="ár" type="xs:int"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="italTipus">
            <xs:sequence>
                <xs:element name="termék" type="xs:string"></xs:element>
                <xs:element name="típus" type="xs:string"></xs:element>
                <xs:element name="ár" type="xs:int"></xs:element>
                <xs:element name="űrtartalom" type="xs:int" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>

</xs:schema>

=== LosoncziDominik/HZ60V1WebXML/HZ60V1_XMLTask/HZ60V1_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<HZ60V1_mozi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="HZ60V1_XSD.xsd">
    
    <!-- Mozik-->

    <mozi Mkod="m1">
    <név>Miskolc Mozi</név>
    <cím>
        <város>Miskolc</város>
        <utca>Fenyőfi</utca>
        <házszám>114.</házszám>
    </cím>
    </mozi>

    <mozi Mkod="m2">
    <név>Classic Mozi</név>
    <cím>
        <város>Hódmezővásárhely</város>
        <utca>Kossuth Lajos</utca>
        <házszám>40.</házszám>
    </cím>
    </mozi>

    <mozi Mkod="m3">
    <név> Mozi</név>
    <cím>
        <város>Miskolc</város>
        <utca>Fenyőfi</utca>
        <házszám>114.</házszám>
    </cím>
    </mozi>

    <!-- Dolgozók-->

    <dolgozó Dkod="d1" M_D="m2">
    <név>Tóth Árpád</név>
    <műszak>Délelőtt</műszak>
    <beosztás>Pénztáros</beosztás>
    </dolgozó>

    <dolgozó Dkod="d2" M_D="m1">
    <név>Lakatos Tihamér</név>
    <műszak>Délután</műszak>
    <beosztás>Takarító</beosztás>
    </dolgozó>

    <dolgozó Dkod="d3" M_D="m1">
    <név>Nagy István</név>
    <műszak>Délután</műszak>
    <beosztás>Biztonsági őr</beosztás>
    </dolgozó>

    <dolgozó Dkod="d4" M_D="m3">
    <név>Hlad Enikő</név>
    <műszak>Délelőtt</műszak>
    <beosztás>Menedzser</beosztás>
    </dolgozó>

    <!-- Termek-->

    <terem Tkod="t1" M_T="m1">
        <férőhely>40</férőhely>
        <típus>Imax</típus>
        <hangrendszer>AuroMax</hangrendszer>
        <extrák>Masszázsszék</extrák>
    </terem>
    
    <terem Tkod="t2" M_T="m3">
        <férőhely>55</férőhely>
        <típus>Normál</típus>
        <hangrendszer>Broadway Surround</hangrendszer>
        <extrák>Nagy lábtér</extrák>
    </terem>

    <terem Tkod="t3" M_T="m2">
        <férőhely>62</férőhely>
        <típus>3DX</típus>
        <hangrendszer>Dolby Atmos</hangrendszer>
        <extrák>Masszázsszék</extrák>
    </terem>

    <terem Tkod="t4" M_T="m2">
        <férőhely>30</férőhely>
        <típus>Normál</típus>
        <hangrendszer>AuroMax</hangrendszer>
        <extrák>Masszázsszék</extrák>
    </terem>

    <terem Tkod="t5" M_T="m3">
        <férőhely>45</férőhely>
        <típus>Imax</típus>
        <hangrendszer>Dolby Atmos</hangrendszer>
        <extrák>Nagy lábtér</extrák>
    </terem>

    <!-- Filmek-->

    <film Fkod="f1" M_F="m2">
        <cím>Ponyvaregény</cím>
        <szereplő>Samuel L. Jackson</szereplő>
        <szereplő>John Travolta</szereplő>
        <szereplő>Bruce Willis</szereplő>
        <hossz>154</hossz>
        <rendező>Quentin Tarantino</rendező>
        <értékelés>8.8</értékelés>
        <év>1994</év>
    </film>

    <film Fkod="f2" M_F="m1">
        <cím>12 dühös ember</cím>
        <szereplő>Henry Fonda</szereplő>
        <szereplő>Lee J. Cobb</szereplő>
        <szereplő>Martin Balsam</szereplő>
        <hossz>96</hossz>
        <rendező>Sydney Lumet</rendező>
        <értékelés>9.0</értékelés>
        <év>1957</év>
    </film>

    <film Fkod="f3" M_F="m1">
        <cím>Harcosok klubja</cím>
        <szereplő>Brad Pitt</szereplő>
        <szereplő>Edward Norton</szereplő>
        <szereplő>Meat Loaf</szereplő>
        <hossz>139</hossz>
        <rendező>David Fincher</rendező>
        <értékelés>8.8</értékelés>
        <év>1999</év>
    </film>

    <film Fkod="f4" M_F="m3">
        <cím>Forrest Gump</cím>
        <szereplő>Tom Hanks</szereplő>
        <szereplő>Robin Wright</szereplő>
        <szereplő>Gary Sinise</szereplő>
        <hossz>142</hossz>
        <rendező>Robert Zemeckis</rendező>
        <értékelés>8.9</értékelés>
        <év>1994</év>
    </film>

    <!-- Vásárlók-->

    <vásárló Vkod="v1" J_V="j3">
        <cím>
            <város>Battonya</város>
            <utca>Kodály Zoltán</utca>
            <házszám>4.</házszám>
        </cím>
        <név>Szerencsi Henrik</név>
        <életkor>26</életkor>
        <foglalás>
            <film_cím>Ponyvaregény</film_cím>
            <időpont>18:00</időpont>
            <nyelv>Magyar</nyelv>    
        </foglalás>
    </vásárló>

    <vásárló Vkod="v2" J_V="j2">
        <cím>
            <város>Makkoshotyka</város>
            <utca>Arany János</utca>
            <házszám>101.</házszám>
        </cím>
        <név>Lajos Sándor</név>
        <életkor>45</életkor>
        <foglalás>
            <film_cím>12 dühös ember</film_cím>
            <időpont>12:00</időpont>
            <nyelv>magyar</nyelv>    
        </foglalás>
    </vásárló>

    <vásárló Vkod="v3" J_V="j1">
        <cím>
            <város>Budapest</város>
            <utca>Árpád</utca>
            <házszám>321.</házszám>
        </cím>
        <név>Kiss Attila</név>
        <életkor>33</életkor>
        <foglalás>
            <film_cím>12 dühös ember</film_cím>
            <időpont>14:00</időpont>
            <nyelv>angol</nyelv>    
        </foglalás>
    </vásárló>

    <!-- Jegyek-->

    <jegy Jkod="j1" M_J="m2">
        <ár>2200</ár>
        <kedvezmény>Nincs</kedvezmény>
    </jegy>

    <jegy Jkod="j2" M_J="m1">
        <ár>1500</ár>
        <kedvezmény>Diák</kedvezmény>
    </jegy>

    <jegy Jkod="j3" M_J="m3">
        <ár>2200</ár>
        <kedvezmény>Nincs</kedvezmény>
    </jegy>

    <!-- Büfék-->

    <büfé Bkod="b1" M_B="m1">
        <étel>
            <termék>Popcorn</termék>
            <típus>Sós</típus>
            <ár>1400</ár>
            <méret>Kicsi</méret>
            <méret>Közepes</méret>
            <méret>Nagy</méret>
        </étel>
        <étel>
            <termék>Popcorn</termék>
            <típus>Vajas</típus>
            <ár>1600</ár>
            <méret>Kicsi</méret>
            <méret>Közepes</méret>
            <méret>Nagy</méret>
        </étel>
        <egyéb>
            <termék>Kitűző</termék>
            <ár>2500</ár>    
        </egyéb>
        <ital>
            <termék>Kóla</termék>
            <típus>Cukormentes</típus>
            <ár>1200</ár>
            <űrtartalom>1000</űrtartalom>
            <űrtartalom>750</űrtartalom>
            <űrtartalom>500</űrtartalom>
        </ital>
        <ital>
            <termék>Fanta</termék>
            <típus>Narancs</típus>
            <ár>1100</ár>
            <űrtartalom>1000</űrtartalom>
            <űrtartalom>750</űrtartalom>
            <űrtartalom>500</űrtartalom>
        </ital>
    </büfé>

    <büfé Bkod="b2" M_B="m2">
        <étel>
            <termék>Popcorn</termék>
            <típus>Vajas</típus>
            <ár>1500</ár>
            <méret>Kicsi</méret>
            <méret>Közepes</méret>
            <méret>Nagy</méret>
        </étel>
        <étel>
            <termék>Nachos</termék>
            <típus>Sajtos</típus>
            <ár>2300</ár>
            <méret>Kicsi</méret>
            <méret>Közepes</méret>
            <méret>Nagy</méret>
        </étel>
        <egyéb>
            <termék>Plakát</termék>
            <ár>4500</ár>
        </egyéb>
        <egyéb>
            <termék>Kitűző</termék>
            <ár>2500</ár>    
        </egyéb>
        <ital>
            <termék>Fanta</termék>
            <típus>Narancs</típus>
            <ár>1100</ár>
            <űrtartalom>1000</űrtartalom>
            <űrtartalom>750</űrtartalom>
            <űrtartalom>500</űrtartalom>
        </ital>
        <ital>
            <termék>Ice Tea</termék>
            <típus>Barackos</típus>
            <ár>1200</ár>
            <űrtartalom>1000</űrtartalom>
            <űrtartalom>750</űrtartalom>
            <űrtartalom>500</űrtartalom>
        </ital>
    </büfé>

    <büfé Bkod="b3" M_B="m1">
        <étel>
            <termék>Nachos</termék>
            <típus>Sajtos</típus>
            <ár>2300</ár>
            <méret>Kicsi</méret>
            <méret>Közepes</méret>
            <méret>Nagy</méret>
        </étel>
        <étel>
            <termék>Gumicukor</termék>
            <típus>Vegyes</típus>
            <ár>2600</ár>
            <méret>Zacskó</méret>
        </étel>
        <egyéb>
            <termék>Figura</termék>
            <ár>5000</ár>    
        </egyéb>
        <ital>
            <termék>Ice Tea</termék>
            <típus>Citromos</típus>
            <ár>1300</ár>
            <űrtartalom>1000</űrtartalom>
            <űrtartalom>750</űrtartalom>
            <űrtartalom>500</űrtartalom>
        </ital>
    </büfé>

</HZ60V1_mozi>
